require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hc_providers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # HcProvider. As you add validations to HcProvider, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HcProvider.create! valid_attributes
      get hc_providers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hc_provider = HcProvider.create! valid_attributes
      get hc_provider_url(hc_provider)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hc_provider_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      hc_provider = HcProvider.create! valid_attributes
      get edit_hc_provider_url(hc_provider)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HcProvider" do
        expect {
          post hc_providers_url, params: { hc_provider: valid_attributes }
        }.to change(HcProvider, :count).by(1)
      end

      it "redirects to the created hc_provider" do
        post hc_providers_url, params: { hc_provider: valid_attributes }
        expect(response).to redirect_to(hc_provider_url(HcProvider.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HcProvider" do
        expect {
          post hc_providers_url, params: { hc_provider: invalid_attributes }
        }.to change(HcProvider, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post hc_providers_url, params: { hc_provider: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hc_provider" do
        hc_provider = HcProvider.create! valid_attributes
        patch hc_provider_url(hc_provider), params: { hc_provider: new_attributes }
        hc_provider.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hc_provider" do
        hc_provider = HcProvider.create! valid_attributes
        patch hc_provider_url(hc_provider), params: { hc_provider: new_attributes }
        hc_provider.reload
        expect(response).to redirect_to(hc_provider_url(hc_provider))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        hc_provider = HcProvider.create! valid_attributes
        patch hc_provider_url(hc_provider), params: { hc_provider: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hc_provider" do
      hc_provider = HcProvider.create! valid_attributes
      expect {
        delete hc_provider_url(hc_provider)
      }.to change(HcProvider, :count).by(-1)
    end

    it "redirects to the hc_providers list" do
      hc_provider = HcProvider.create! valid_attributes
      delete hc_provider_url(hc_provider)
      expect(response).to redirect_to(hc_providers_url)
    end
  end
end
